# Site settings
title: Baba Malik Hussain
description: Data Engineer
author:
  name: Baba Malik Hussain
  email: babamalik206@gmail.com
  linkedin: https://www.linkedin.com/in/babamalik
  github: https://github.com/BabaMalik

# Build settings
baseurl: ""
url: "https://babamalik.github.io"
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:title

# Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
