title: "Baba Malik Hussain - Data Engineer Portfolio"
description: "Professional portfolio of Baba Malik Hussain, showcasing expertise in Azure, Databricks, PySpark, and SQL."
author: "Baba Malik Hussain"
baseurl: ""
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL
theme: minima
markdown: kramdown
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-sitemap
